<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Västra Götalandsregion licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='SendMedicalRecordsInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:riv:ehr:patientsummary:SendMedicalRecordsResponder:1' xmlns:tjsi='urn:riv:ehr:patientsummary:SendMedicalRecordsInitiator:1' xmlns:tns='urn:riv:ehr:patientsummary:SendMedicalRecords:1:rivtabp21' targetNamespace='urn:riv:ehr:patientsummary:SendMedicalRecords:1:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: SendMedicalRecordsInteraction
			 Beskrivning: 
			 Submission of medical record to medical records system within Västra Götalandsregionen
			 Revisioner: 
			 Tjänstedomän: ehr:patientsummary
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP21
			 Förvaltas av: Västra Götalandsregion
			 </xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:ehr:patientsummary:SendMedicalRecords:1:rivtabp21'>
      <xs:import schemaLocation='SendMedicalRecordsResponder_1.1.xsd' namespace='urn:riv:ehr:patientsummary:SendMedicalRecordsResponder:1' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='SendMedicalRecordsRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>The organisation number of the receiving part</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:SendMedicalRecords' />
  </wsdl:message>
  <wsdl:message name='SendMedicalRecordsResponse'>
    <wsdl:part name='parameters' element='tjsr:SendMedicalRecordsResponse' />
  </wsdl:message>
  <wsdl:portType name='SendMedicalRecordsResponderInterface'>
    <wsdl:operation name='SendMedicalRecords'>
      <wsdl:input message='tns:SendMedicalRecordsRequest' />
      <wsdl:output message='tns:SendMedicalRecordsResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='SendMedicalRecordsResponderBinding' type='tns:SendMedicalRecordsResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='SendMedicalRecords'>
      <soap:operation soapAction='urn:riv:ehr:patientsummary:SendMedicalRecordsResponder:1:SendMedicalRecords' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:SendMedicalRecordsRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='SendMedicalRecordsResponderService'>
    <wsdl:port name='SendMedicalRecordsResponderPort' binding='tns:SendMedicalRecordsResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>